# Generated by Django 2.2.5 on 2019-10-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='nivel_quizz',
            field=models.IntegerField(blank=True, choices=[(3, 'Alto'), (2, 'Medio'), (1, 'Bajo')], null=True),
        ),
    ]
