# Generated by Django 2.2.5 on 2019-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_nivel_quizz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lvl_dificultad',
            field=models.IntegerField(blank=True, choices=[(3, 'Alto'), (2, 'Medio'), (1, 'Bajo')], null=True, verbose_name='Nivel dificultad de la pregunta'),
        ),
    ]
