# Generated by Django 2.2.5 on 2019-11-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0012_nivel'),
        ('quiz', '0005_question_lvl_dificultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lvl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.Nivel'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='prueba_nivelacion',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.Unidad'),
        ),
    ]
