# Generated by Django 2.2.7 on 2019-11-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20191117_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='prueba_nivelacion',
            field=models.NullBooleanField(default=False),
        ),
    ]
