# Generated by Django 2.2.5 on 2019-10-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20191017_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='usercreado',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='apoderados',
            name='usercreado',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
