# Generated by Django 2.2.5 on 2019-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_auto_20191017_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='usercreado',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
