# Generated by Django 2.2.5 on 2019-10-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190914_1551'),
        ('Registro', '0004_profesor_usercreado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acomulado', models.CharField(max_length=3)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.Alumno')),
                ('codigo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
    ]
