# Generated by Django 2.2.5 on 2019-10-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_auto_20191017_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntaje',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.Alumno'),
        ),
    ]
