# Generated by Django 2.2.5 on 2019-11-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0010_auto_20191103_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='lvls',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
