# Generated by Django 2.2.7 on 2019-11-26 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0013_asignatura_materia'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='puntaje',
            managers=[
                ('puntajes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='materia',
        ),
        migrations.AddField(
            model_name='nivel',
            name='porcentajeaprovacion',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nivel',
            name='porcentajeminimo',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='porcentajesasignados',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='pruebanivelacion',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='RindePrueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.PositiveIntegerField(null=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.Alumno')),
            ],
            managers=[
                ('rindepruebas', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NivelAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.Alumno')),
                ('nivel_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.Nivel')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.Unidad')),
            ],
            managers=[
                ('niveles_asignados', django.db.models.manager.Manager()),
            ],
        ),
    ]
