# Generated by Django 2.2.7 on 2019-11-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0015_asignatura_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='porcentajesasignados',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='pruebanivelacion',
            field=models.NullBooleanField(default=False),
        ),
    ]
